language: go

go:
- 1.5

before_install:
- export CIAEON=$(curl -s https://api.travis-ci.org/builds/$TRAVIS_BUILD_ID | jq '.message|contains("CIAEON=true")')

install:
- go get -t -v ./...

script:
- go test -v ./...
